const NO_GAME = -1;
const STATUS_MENU = 0;
const STATUS_WAITING = 1;
const STATUS_INGAME = 2;
const MAX_USERNAME_LENGTH = 13;


module.exports = {
    NO_GAME: NO_GAME,
    STATUS_MENU : STATUS_MENU,
    STATUS_WAITING : STATUS_WAITING,
    STATUS_INGAME: STATUS_INGAME,
    MAX_USERNAME_LENGTH : MAX_USERNAME_LENGTH
}